# Autograd with tensors

In [ ]:
import torch

In [ ]:
w = torch.randn(4,3,requires_grad=True)

In [ ]:
w

tensor([[ 0.5679,  1.2830,  0.7046],
        [-0.0390, -0.9265,  2.2788],
        [ 1.6065,  0.9632,  0.0984],
        [ 0.4938,  1.1908,  0.4797]], requires_grad=True)

In [ ]:
w.requires_grad_(False)

tensor([[ 0.5679,  1.2830,  0.7046],
        [-0.0390, -0.9265,  2.2788],
        [ 1.6065,  0.9632,  0.0984],
        [ 0.4938,  1.1908,  0.4797]])

In [ ]:
w.requires_grad_(True)

tensor([[ 0.5679,  1.2830,  0.7046],
        [-0.0390, -0.9265,  2.2788],
        [ 1.6065,  0.9632,  0.0984],
        [ 0.4938,  1.1908,  0.4797]], requires_grad=True)

In [ ]:
y = torch.exp(w)
y

tensor([[1.7646, 3.6075, 2.0230],
        [0.9618, 0.3959, 9.7653],
        [4.9852, 2.6200, 1.1034],
        [1.6385, 3.2897, 1.6156]], grad_fn=<ExpBackward>)

In [ ]:
print(y.grad_fn)

In [ ]:
outp = y.mean()
outp

tensor(2.8142, grad_fn=<MeanBackward0>)

In [ ]:
print(w.grad)

None


In [ ]:
outp.backward()

In [ ]:
print(w.grad)

tensor([[0.1470, 0.3006, 0.1686],
        [0.0801, 0.0330, 0.8138],
        [0.4154, 0.2183, 0.0920],
        [0.1365, 0.2741, 0.1346]])


In [ ]:
w.detach() #Gradients for this tensor wont be updated

tensor([[ 0.5679,  1.2830,  0.7046],
        [-0.0390, -0.9265,  2.2788],
        [ 1.6065,  0.9632,  0.0984],
        [ 0.4938,  1.1908,  0.4797]])

In [ ]:
outp.requires_grad

True

In [ ]:
with torch.no_grad():
  outp=(w+y).mean()

In [ ]:
outp.requires_grad # Hence tracking history prevented

False