# Tensors 

In [ ]:
import torch

## zeros()

In [ ]:
w=torch.zeros(4,3)

In [ ]:
w

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## size() and shape

In [ ]:
w.size()

torch.Size([4, 3])

In [ ]:
w.shape

torch.Size([4, 3])

## randn() and randn_like()

In [ ]:
w = torch.randn(4,3)

In [ ]:
w

tensor([[ 0.6157, -0.5712, -0.3327],
        [-0.4782,  0.7792,  1.3506],
        [ 0.3153, -0.1099, -0.1693],
        [ 0.6108,  0.0700, -0.2134]])

In [ ]:
t = torch.randn_like(w) # randn like that of w ?
t

tensor([[-0.3481,  0.3528, -1.1913],
        [-0.3233, -0.3784,  1.2145],
        [ 2.5904,  0.9232, -0.4477],
        [ 0.3255, -2.5791,  0.1040]])

## fill_()

In [ ]:
w.fill_(1) # fills w with 1's in-place

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
w

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## view()

In [ ]:
t = w.view(3,4)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
w.view(3,-1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## numpy()

In [ ]:
w.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [ ]:
type(w.numpy())

numpy.ndarray